sudo:
  false

language:
  python

python:
  - 2.7

services:
  - postgresql

addons:
  postgresql: '9.4'

env:
  global:
    - TEST_WAREHOUSE_URL=postgres://postgres@localhost:5432/opentrials_warehouse_test

install:
  - pip install tox
  - psql -c 'create database opentrials_warehouse_test;' -U postgres

script:
  - make test
